<a href="https://colab.research.google.com/github/nbokadia/simple-python-mysql-connector/blob/main/Survey.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df = pd.read_csv('/content/survey_results_public.csv', index_col = 'Respondent') #or use df.set_index('', inplace = True)
schema_df= pd.read_csv('/content/survey_results_schema.csv', index_col = 'Column')

In [4]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3088 entries, 1 to 3101
Data columns (total 60 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   MainBranch                    3088 non-null   object
 1   Hobbyist                      3088 non-null   object
 2   Age                           2709 non-null   float64
 3   Age1stCode                    3065 non-null   object
 4   CompFreq                      2294 non-null   object
 5   CompTotal                     2138 non-null   float64
 6   ConvertedComp                 2131 non-null   float64
 7   Country                       3088 non-null   object
 8   CurrencyDesc                  2563 non-null   object
 9   CurrencySymbol                2563 non-null   object
 10  DatabaseDesireNextYear        2331 non-null   object
 11  DatabaseWorkedWith            2653 non-null   object
 12  DevType                       2705 non-null   object
 13  EdLevel                       3018 non-null   object
 14  Employment                    3074 non-null   object
 15  Ethnicity                     2753 non-null   object
 16  Gender                        2940 non-null   object
 17  JobFactors                    2798 non-null   object
 18  JobSat                        2553 non-null   object
 19  JobSeek                       2906 non-null   object
 20  LanguageDesireNextYear        2861 non-null   object
 21  LanguageWorkedWith            3054 non-null   object
 22  MiscTechDesireNextYear        2335 non-null   object
 23  MiscTechWorkedWith            2261 non-null   object
 24  NEWCollabToolsDesireNextYear  2584 non-null   object
 25  NEWCollabToolsWorkedWith      2915 non-null   object
 26  NEWDevOps                     2492 non-null   object
 27  NEWDevOpsImpt                 2452 non-null   object
 28  NEWEdImpt                     2702 non-null   object
 29  NEWJobHunt                    2519 non-null   object
 30  NEWJobHuntResearch            2450 non-null   object
 31  NEWLearn                      2974 non-null   object
 32  NEWOffTopic                   2914 non-null   object
 33  NEWOnboardGood                2491 non-null   object
 34  NEWOtherComms                 3067 non-null   object
 35  NEWOvertime                   2531 non-null   object
 36  NEWPurchaseResearch           2064 non-null   object
 37  NEWPurpleLink                 3042 non-null   object
 38  NEWSOSites                    3069 non-null   object
 39  NEWStuck                      3042 non-null   object
 40  OpSys                         3056 non-null   object
 41  OrgSize                       2499 non-null   object
 42  PlatformDesireNextYear        2711 non-null   object
 43  PlatformWorkedWith            2905 non-null   object
 44  PurchaseWhat                  2290 non-null   object
 45  Sexuality                     2698 non-null   object
 46  SOAccount                     3033 non-null   object
 47  SOComm                        3031 non-null   object
 48  SOPartFreq                    2696 non-null   object
 49  SOVisitFreq                   3033 non-null   object
 50  SurveyEase                    3057 non-null   object
 51  SurveyLength                  3049 non-null   object
 52  Trans                         2905 non-null   object
 53  UndergradMajor                2752 non-null   object
 54  WebframeDesireNextYear        2136 non-null   object
 55  WebframeWorkedWith            2316 non-null   object
 56  WelcomeChange                 2957 non-null   object
 57  WorkWeekHrs                   2446 non-null   float64
 58  YearsCode                     3063 non-null   object
 59  YearsCodePro                  2572 non-null   object
dtypes: float64(4), object(56)
memory usage: 1.4+ MB

In [5]:
pd.set_option('display.max_columns',61)
pd.set_option('display.max_rows',61)

In [6]:
df.head(5)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,NaN,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not at all important/not necessary,Curious about other opportunities;Wanting to w...,NaN,Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Linux-based,20 to 99 employees,NaN,NaN,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

In [7]:
schema_df.sort_index(inplace=True)
schema_df.head()

                                                    QuestionText
Column
Age            What is your age (in years)? If you prefer not...
Age1stCode     At what age did you write your first line of c...
CompFreq        Is that compensation weekly, monthly, or yearly?
CompTotal      What is your current total compensation (salar...
ConvertedComp  Salary converted to annual USD salaries using ...

In [8]:
schema_df.loc['WelcomeChange','QuestionText']

'Compared to last year, how welcome do you feel on Stack Overflow?'

In [9]:
df['Hobbyist'].value_counts()

df.loc[1:2, 'Hobbyist':'Employment']

,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment
Respondent,,,,,,,,,,,,,,
1,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em..."
2,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time

In [10]:
filt = (df['Hobbyist'] == 'Yes')

In [11]:
df[filt].head(2)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN

In [12]:
Countries = ['India','United States','Germany']
filt = df['Country'].isin(Countries)
filt1 = df['LanguageWorkedWith'].str.contains('Python', na= False)

In [13]:
df.loc[filt, 'Country']

Respondent
1             Germany
5       United States
6             Germany
7               India
8       United States
            ...
3097    United States
3098    United States
3099    United States
3100    United States
3101    United States
Name: Country, Length: 1796, dtype: object

In [14]:
df.loc[filt1, 'LanguageWorkedWith']

Respondent
3                                Objective-C;Python;Swift
8                                              Python;SQL
10                    HTML/CSS;Java;JavaScript;Python;SQL
13                                    C;JavaScript;Python
15       Bash/Shell/PowerShell;C;HTML/CSS;Java;Python;SQL
                              ...
3094    Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...
3095    C#;HTML/CSS;Java;JavaScript;Python;SQL;TypeScript
3097             HTML/CSS;Java;JavaScript;Python;Ruby;SQL
3098                              JavaScript;Python;R;SQL
3099    Bash/Shell/PowerShell;HTML/CSS;JavaScript;Pyth...
Name: LanguageWorkedWith, Length: 1357, dtype: object

In [15]:
df.rename(columns={'CurrencySymbol': 'Currency'}, inplace = True)

In [16]:
df['Currency']

Respondent
1       EUR
2       GBP
3       NaN
4       ALL
5       NaN
       ...
3097    NaN
3098    USD
3099    USD
3100    USD
3101    USD
Name: Currency, Length: 3088, dtype: object

In [17]:
df['Hobbyist'].apply(lambda x: x.lower())
df['Hobbyist'].apply(len)
#len(df['Hobbyist'])

Respondent
1       3
2       2
3       3
4       3
5       3
       ..
3097    3
3098    3
3099    3
3100    3
3101    3
Name: Hobbyist, Length: 3088, dtype: int64

In [18]:
df['Hobbyist']

Respondent
1       Yes
2        No
3       Yes
4       Yes
5       Yes
       ...
3097    Yes
3098    Yes
3099    Yes
3100    Yes
3101    Yes
Name: Hobbyist, Length: 3088, dtype: object

In [19]:
df['Hobbyist'] = df['Hobbyist'].map({'Yes': 'True', 'No': 'False'})
df['Hobbyist']

Respondent
1        True
2       False
3        True
4        True
5        True
        ...
3097     True
3098     True
3099     True
3100     True
3101     True
Name: Hobbyist, Length: 3088, dtype: object

In [20]:
df['CurrencyDesc'].str.split(' ', expand=True)
#df[['con','curr','q','w','e']] == df['CurrencyDesc'].str.split(' ', expand=True)

                   0         1       2     3     4
Respondent
1           European      Euro    None  None  None
2              Pound  sterling    None  None  None
3                NaN       NaN     NaN   NaN   NaN
4           Albanian       lek    None  None  None
5                NaN       NaN     NaN   NaN   NaN
...              ...       ...     ...   ...   ...
3097             NaN       NaN     NaN   NaN   NaN
3098          United    States  dollar  None  None
3099          United    States  dollar  None  None
3100          United    States  dollar  None  None
3101          United    States  dollar  None  None

[3088 rows x 5 columns]

In [21]:
filt = df['Gender']=='Male'
filt1 = df['Gender']=='Female'

In [22]:
df.drop(index=1)
df.drop(index=df[filt].index, inplace=True)

In [23]:
df['Gender']

Respondent
1       Man
2       NaN
3       NaN
4       Man
5       Man
       ...
3097    Man
3098    Man
3099    Man
3100    Man
3101    Man
Name: Gender, Length: 3088, dtype: object

In [24]:
df.sort_values(by='Country', ascending=True)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,Currency,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2932,I am a developer by profession,False,NaN,14,Yearly,60000.0,16335.0,Afghanistan,United Arab Emirates dirham,AED,NaN,MongoDB;MySQL,"Database administrator;Developer, back-end;Dev...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,Industry that I’d be working in;Diversity of t...,Very satisfied,I am not interested in new job opportunities,NaN,JavaScript,NaN,Node.js;React Native,NaN,Gitlab,No,Extremely important,Very important,Just because;Having a bad day (or week or mont...,"Read company media, such as employee blogs or ...",Once every few years,Yes,Yes,No,Often: 1-2 days per week or more,Read ratings or reviews on third party sites l...,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,MacOS,2 to 9 employees,NaN,Android;AWS;iOS,I have a great deal of influence,NaN,No,"No, not at all",NaN,Multiple times per day,Easy,Appropriate in length,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,90.0,4,2
898,I am a developer by profession,True,NaN,NaN,Monthly,NaN,NaN,Afghanistan,Australian dollar,AUD,NaN,NaN,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,"Indigenous (such as Native American, Pacific I...","Non-binary, genderqueer, or gender non-conforming",Flex time or a flexible schedule,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,Yes,Somewhat important,Very important,Trouble with leadership at my company,Directly asking current or past employees at t...,NaN,NaN,No,Yes,Sometimes: 1-2 days per month but less than we...,NaN,Indifferent,Stack Overflow Talent (for hiring companies/re...,Visit another developer community (please name):,NaN,10 to 19 employees,NaN,NaN,I have some influence,Gay or Lesbian,NaN,NaN,NaN,NaN,Neither easy nor difficult,Appropriate in length,No,"A natural science (such as biology, chemistry,...",NaN,NaN,NaN,NaN,4,3
4,I am a developer by profession,True,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,NaN,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not at all important/not necessary,Curious about other opportunities;Wanting to w...,NaN,Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Linux-based,20 to 99 employees,NaN,NaN,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
564,I am a developer by profession,True,22.0,18,Monthly,102000.0,10812.0,Albania,Albanian lek,ALL,DynamoDB;Elasticsearch;Firebase;Redis,Oracle,"Database administrator;Designer;Developer, bac...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Flex time or a flexible schedule;Languages, fr...",Very satisfied,"I’m not actively looking, but I am open to new...",Python;Scala;SQL,Bash/Shell/PowerShell;Java;Python;SQL,Pandas,Pandas,Github;Gitlab;Slack,Confluence;Github;Gitlab;Slack,Not sure,Extremely important,Somewhat important,Wanting to share accomplishments with a wider ...,"Read company media, such as employee blogs or ...",Every few months,Not sure,Yes,Yes,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Do other work and come ba...,Linux-based,10 to 19 employees,AWS;Docker;Google Cloud Platform;Linux,Docker;Linux,I have a great deal of influence,NaN,Yes,"Yes, definitely",A few times per week,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Flask,Spring,Just as welcome now as I felt last year,45.0,3,2
2010,I am a student who is learning to code,True,24.0,18,NaN,NaN,NaN,Algeria,NaN,NaN,Cassandra;MongoDB;MySQL,MySQL;Oracle,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Student,Biracial,Man,"Industry that I’d be working in;Languages, fra...",NaN,"I’m not actively looking, but I am open to new...",C;C++;Go;Java;Python;R,C;Java;Python;SQL,Keras;TensorFlow;Unreal Engine,Keras;TensorFlow,Github;Stack Overflow for Teams,Github,NaN,NaN,NaN,NaN,NaN,Once a year,Yes,NaN,Yes,NaN,Visit developer communities like Stack Overflo...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Watch help / t...,Linux-based,NaN,Linux,Linux;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,Daily or almost daily,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django,Django,Just as welcome now as I felt last year,NaN,6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2243,I am a student who is learning to code,True,19.0,16,NaN,NaN,NaN,"Venezuela, Bolivarian Republic of...",NaN,NaN,MongoDB;PostgreSQL,SQLite,NaN,"Secondary school (e.g. American high school, G...",Student,Hispanic or Latino/a/x,Man,"Industry that I’d be working in;Languages, fra...",NaN,"I’m not actively looking, but I am open to new...",C++,C;JavaScript;Python,Node.js;Unity 3D;Unreal Engine,NaN,Github;Slack;Trello,"Google Suite (Docs, Meet, etc)",NaN,NaN,NaN,NaN,NaN,Every few months,Yes,NaN,No,NaN,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Visit another developer c...,Windows,NaN,Arduino;Docker;Kubernetes;Linux;Raspberry Pi,Windows,NaN,Straight / Heterosexual,No,"No, not really",NaN,A few times per week,Easy,Too long,No,NaN,NaN,NaN,Just as welcome now as I felt last year,NaN,3,NaN
657,I am a developer by profession,True,21.0,17,NaN,NaN,NaN,"Venezuela, Bolivarian Republic of...",NaN,NaN,MySQL;SQLite,MySQL,"Academic researcher;Designer;Developer, front-end",Some college/university study without earning ...,"Not employed, but looking for work",Hispanic or Latino/a/x,Man,"Industry that I’d be working in;Languages, fra...",NaN,I am actively looking for a job,Haskell;HTML/CSS;JavaScript;SQL,C#;C++;Haskell;HTML/CSS;Java;JavaScript;PHP;Py...,Node.js;Unity 3D,Node.js;React Native,Github;Gitlab;Trello,"Github;Gitlab;Slack;Trello;Google Suite (Docs,...",NaN,NaN,Fairly important,Curious about other opportunities;Better compe...,Company reviews from third party sites (e.g. G...,Every few months,Not sure,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Go for a walk ...,Windows,NaN,Heroku;Linux;Windows,Linux;Windows;WordPress,NaN,NaN,Yes,"No, not really",Less than once per month or monthly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;React.js,Express;jQuery;Laravel;React.js;Vue.js,Somewhat more welcome now than last year,NaN,4,NaN
822,I am a developer by profession,False,20.0,18,Monthly,300.0,3600.0,"Venezuela, Bolivarian Republic of...",United States dollar,USD,Firebase;SQLite,MariaDB;MongoDB;MySQL,"Developer, back-end;Developer, front-end","Secondary school (e.g. American high school, G...","Independent contractor, freelancer, or self-em...",Hispanic or Latino/a/x,Man,"Languages, frameworks, and other technologies ...",Slightly dissatisfied,I am actively looking for a job,NaN,HTML/CSS;JavaScript;PHP;TypeScript,Flutter;React Native,Cordova;Node.js,Jira,Github;Trello,Not sure,Extremely important,Not at all important/not necessary,Better compensation;Trouble with my direct man...,"Read company media, such as employee blogs or ...",Every few months,Not sure,No,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Meditate;Visit Stack Overflow;Watch help / tut...,Windows,"Just me - I am a freelancer, sole proprietor, ...",Android;AWS;Docker;Kubernetes;Microsoft Azure,Heroku;WordPress,NaN,Straight / Heterosexual,Yes,Neutral,Less than once per month or monthly,Multiple times per day,Easy,Too long,No,NaN,Django;Vue.js,Angular;Express;Gatsby;jQuery;Laravel;React.js,Just as welcome now as I felt last year,35.0,2,2
2476,I am a developer by profession,True,30.0,15,Monthly,30000000.0,15528.0,Viet Nam,Vietnamese dong,VND,Firebase;MongoDB;MySQL;Redis,Firebase;MongoDB;MySQL;PostgreSQL;Redis,"Developer, full-stack;System administrator","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",Southeast Asian,Man,"Flex time or a flexible schedule;Languages, fr...",Very dissatisfied,I am actively looking for a job,HTML/CSS;JavaScript;PHP;Python;SQL,C#;Go;HTML/CSS;JavaScript;Objective-C;PHP;Pyth...,Node.js,.NET;Cordova;Node.js,"Github;Gitlab;Slack;Google Suite (Docs, Meet, ...","Github;Gitlab;Slack;Google Suite (Docs, Meet, ...",No,Somewhat important,Somewhat important,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Onboarding? What onboarding?,Yes,Rarely: 1-2 days per year or less,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Meditate;Call a coworker or friend;Visit Stack...,Linux-based,"Just me - I am a freelancer, sole proprietor, ...",AWS;Docker;Linux;MacOS;Raspberry Pi;WordPress,AWS;Docker;Google Cloud Platform;Heroku;iOS;Li...,NaN,Straight / Heterosexual,Yes,"Yes, definitely",Daily or almost daily,Daily or almost daily,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery;Laravel;Vue.js,Angular;ASP.NET;Django;jQuery;Laravel;Ruby on ...,Somewhat more welcome now than last year,20.0,11,9
826,I am a student who is learning to code,True,NaN,18,NaN,NaN,NaN,Viet Nam,NaN,NaN,NaN,Microsoft SQL Server;MySQL,NaN,"Secondary school (e.g. American high school, G...",Student,East Asian,Man,Industry that I’d be working in;Diversity of t...,NaN,I am actively looking for a job,NaN,C;C#;HTML/CSS;Java;Python,TensorFlow;Torch/PyTorch,TensorFlow,Github;Microsoft Azure,Github;Microsoft Azure,NaN,NaN,NaN,NaN,NaN,Once a year,Not sure,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow,Windows,NaN,AWS;Google Cloud Platform;Heroku;Linux;Microso...,Google Cloud Platform;Heroku;Microsoft Azure,NaN,Straight / Heterosexual,Yes,"Yes, definitely",A few times per week,A few times per week,Neither easy nor difficult,Too long,No,NaN,Flask,Flask,Just as welcome now as I felt last year,NaN,3,NaN

In [25]:
df['ConvertedComp'].nlargest(10)

Respondent
123     2000000.0
125     2000000.0
193     2000000.0
665     2000000.0
699     2000000.0
724     2000000.0
818     2000000.0
986     2000000.0
1022    2000000.0
1036    2000000.0
Name: ConvertedComp, dtype: float64

In [26]:
df.nlargest(10, 'ConvertedComp')

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,Currency,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
123,I am a developer by profession,True,26.0,12,Weekly,120000.0,2000000.0,United States,United States dollar,USD,Cassandra;Firebase;MongoDB;PostgreSQL;Redis,Cassandra,"Developer, back-end;Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Neither satisfied nor dissatisfied,"I’m not actively looking, but I am open to new...",C;C++;Go;Kotlin;Rust,Bash/Shell/PowerShell;C++;Go;Java;Python,Flutter;Hadoop;TensorFlow;Unreal Engine,.NET Core,Confluence;Jira;Github;Slack,Confluence;Jira;Github;Gitlab;Slack;Microsoft ...,Yes,Somewhat important,Very important,Trouble with my direct manager;Trouble with le...,"Read company media, such as employee blogs or ...",Once a year,Yes,No,No,Rarely: 1-2 days per year or less,Start a free trial;Ask developers I know/work ...,Indifferent,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,Linux-based,"10,000 or more employees",Android;Arduino;AWS;Docker;Google Cloud Platfo...,AWS;Docker;Linux;Raspberry Pi,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,Daily or almost daily,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Flask;jQuery;React.js,Spring,Just as welcome now as I felt last year,36.0,8,3
125,"I am not primarily a developer, but I write co...",True,41.0,30,Monthly,200000.0,2000000.0,United States,United States dollar,USD,PostgreSQL,PostgreSQL,Data scientist or machine learning specialist;...,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;Family friend...,Very satisfied,I am not interested in new job opportunities,Python,Python;SQL,Keras;Pandas;TensorFlow;Torch/PyTorch,Keras;Pandas;TensorFlow,Jira,Jira,Not sure,Neutral,Critically important,Better work/life balance,Personal network - friends or family;Directly ...,Once every few years,No,Yes,No,Occasionally: 1-2 days per quarter but less th...,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,Windows,"5,000 to 9,999 employees",Docker;Kubernetes,Docker,I have little or no influence,Straight / Heterosexual,Not sure/can't remember,"No, not really",NaN,Multiple times per day,Easy,Appropriate in length,No,NaN,NaN,NaN,Just as welcome now as I felt last year,40.0,11,11
193,I am a developer by profession,True,29.0,16,Weekly,120000.0,2000000.0,United States,United States dollar,USD,NaN,NaN,"Developer, mobile","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,White or of European descent,Man,Specific department or team I’d be working on;...,Very satisfied,"I’m not actively looking, but I am open to new...",Objective-C;Swift,Java;JavaScript;Objective-C;Swift,NaN,NaN,"Github;Slack;Trello;Google Suite (Docs, Meet, ...",Github;Gitlab;Slack;Microsoft Teams;Trello;Goo...,No,Neutral,Fairly important,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",Every few months,No,Onboarding? What onboarding?,No,Never,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Do other work ...,MacOS,10 to 19 employees,Android;iOS,Android;iOS,I have little or no influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,A few times per week,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,40.0,13,7
665,I am a developer by profession,True,24.0,13,Weekly,150000.0,2000000.0,United States,United States dollar,USD,NaN,PostgreSQL,"Developer, front-end","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,Black or of African descent;Biracial,Woman,Diversity of the company or organization;Flex ...,Very satisfied,I am not interested in new job opportunities,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;Python;Ruby,Node.js,Node.js,"Jira;Github;Slack;Google Suite (Docs, Meet, etc)","Jira;Github;Slack;Google Suite (Docs, Meet, etc)",Yes,Extremely important,Somewhat important,Better compensation;Trouble with leadership at...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,Indifferent,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,MacOS,"1,000 to 4,999 employees",AWS;Google Cloud Platform;Kubernetes;Linux;Mac...,Google Cloud Platform;Heroku;MacOS;WordPress,I have little or no influence,Bisexual;Queer,Yes,"No, not really",I have never participated in Q&A on Stack Over...,A few times per month or weekly,Neither easy nor difficult,Appropriate in length,No,"A humanities discipline (such as literature, h...",React.js,Express;React.js;Ruby on Rails,Just as welcome now as I felt last year,40.0,4,Less than 1 year
699,"I am not primarily a developer, but I write co...",True,39.0,16,Weekly,52000.0,2000000.0,United States,United States dollar,USD,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MySQL,System administrator,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,Diversity of the company or organization;Offic...,Slightly satisfied,I am actively looking for a job,Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;J...,Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;J...,.NET;.NET Core;Pandas;Puppet;Unreal Engine,NaN,Microsoft Teams;Microsoft Azure;Trello;Google ...,Jira;Microsoft Teams;Microsoft Azure;Trello;Go...,No,Somewhat important,Critically important,Growth or leadership opportunities,"Read company media, such as employee blogs or ...",Once a year,NaN,No,No,Often: 1-2 days per week or more,Start a free trial;Visit developer communities...,"Hello, old friend",I have never visited any of these sites,Call a coworker or friend;Visit Stack Overflow...,Windows,100 to 499 employees,Android;Arduino;AWS;Google Cloud Platform;Kube...,WordPress,NaN,Straight / Heterosexual,NaN,NaN,NaN,NaN,Neither easy nor difficult,Appropriate in length,No,"Information systems, information technology, o...",Angular;ASP.NET;ASP.NET Core;Express;Flask,NaN,NaN,40.0,5,2
724,"I am not primarily a developer, but I write co...",True,NaN,12,Weekly,103000.0,2000000.0,United States,United States dollar,USD,NaN,MongoDB,"Developer, back-end;Engineer, data;System admi...",Some college/university study without earning ...,Employed full-time,Black or of African descent,Man,Flex time or a flexible schedule;Remote work o...,Very dissatisfied,"I’m not actively looking, but I am open to new...",NaN,JavaScript,NaN,Node.js,NaN,Slack,Not sure,Neutral,Critically important,Growth or leadership opportunities,"Read other media like news articles, founder p...",Once every few years,No,No,No,Often: 1-2 days per week or more,NaN,Indifferent,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,100 to 499 employees,NaN,Docker;Google Cloud Platform,I have little or no influence,Straight / Heterosexual,Yes,"No, not at all",I have never participated in Q&A on Stack Over...,A few times per month or weekly,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,React.js,Not applicable - I did not use Stack Overflow ...,40.0,3,3
818,"I am not primarily a developer, but I write co...",True,40.0,15,Weekly,70000.0,2000000.0,United States,United States dollar,USD,PostgreSQL;Redis;SQLite,IBM DB2;MySQL;PostgreSQL;SQLite,Data or business analyst,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very dissatisfied,I am actively looking for a job,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,Bash/Shell/PowerShell;HTML/CSS;Java;Python;SQL...,.NET;Ansible;Chef;Node.js;Pandas;TensorFlow,NaN,Confluence;Jira;Github;Gitlab;Slack;Microsoft ...,Confluence;Github,No,Somewhat important,Fairly important,Having a bad day (or week or month) at work;Be...,"Read company media, such as employee blogs or ...",Once a year,No,No,No,Occasionally: 1-2 days per quarter but less th...,Ask developers I know/work with;Visit develope...,Indifferent,Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,Linux-based,100 to 499 employees,Android;AWS;Docker;Google Cloud Platform;Linux...,AWS;Heroku;Linux;Raspberry Pi,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per week,Multiple times per day,Easy,Appropriate in length,No,"A social science (such as anthropology, psycho...",Angular;Flask;Spring,NaN,Somewhat less welcome now than last year,40.0,25,2
986,I am a developer by profession,True,27.0,11,Weekly,81000.0,2000000.0,United States,United States dollar,USD,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,"Database administrator;Designer;Developer, bac...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Flex time or a flexible schedule;Languages, fr...",Very satisfied,"I’m not actively looking, but I am open to new...",C++;HTML/CSS;JavaScript;PHP;TypeScript,C;C++;HTML/CSS;Java;JavaScript;Objective-C;PHP...,Node.js,Cordova;Node.js;React Native,Github;Gitlab;Stack Overflow for Teams,Github;Gitlab;Stack Overflow for Teams,No,Somewhat important,Not at all important/not necessary,Better compensation;Trouble with my direct man...,"Read company media, such as employee blogs or ...",Once a year,No,Yes,Yes,Rarely: 1-2 days per year or less,Ask developers I know/work with;Visit develope...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,"1,000 to 4,999 employees",Android;Arduino;AWS;Docker;Linux;Raspberry Pi;...,Android;Arduino;AWS;iOS;Linux;MacOS;Raspberry ...,I have some influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,Easy,Too long,No,"Computer science, computer engineering, or sof...",Express;Laravel,Express;jQuery;Laravel,Just as welcome now as I felt last year,40.0,16,8
1022,I am a developer by profession,True,34.0,16,Weekly,142000.0,2000000.0,United States,United States dollar,USD,Elasticsearch;MongoDB;PostgreSQL;Redis,MongoDB;PostgreSQL,"Developer, full-stack","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,HTML/CSS;JavaScript;Scala;SQL;TypeScript,HTML/CSS;Java;JavaScript;Scala;SQL;TypeScript,Apache Spark;Node.js,Node.js,"Github;Trello;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Trello;Google Sui...,Yes,Extremely important,Very important,Having a bad day (or week or month) at work;Be...,Company reviews from third party sites (e.g. G...,Once every few years,Not sure,No,No,Rarely: 1-2 days per year or less,NaN,Annoyed,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,MacOS,100 to 499 employees,AWS;Docker;Kubernetes,AWS;Docker;Heroku,I have little or no influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Easy,Too long,No,"Computer science, computer engineering, or sof...",React.js,Angular;Angular.js;React.js;Vue.js,Just as welcome now as I felt last year,40.0,18,13
1036,I am a developer by profession,True,26.0,11,Weekly,68500.0,2000000.0,United States,United States dollar,USD,MongoDB;PostgreSQL,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,"Database administrator;Developer, back-end;Dev...","Associate degree (A.A., A.S., etc.)",Employed full-time,White or of European descent;Indigenous (such ...,Man,Remote work options;Office environment or comp...,Slightly satisfied,I am not interested in new job opportunities,C#;JavaScript;Perl;TypeScript,C;C#;HTML/CSS;Java;JavaScript;Perl;PHP;SQL;Typ...,.NET Core;Node.js;Xamarin,.NET;.NET Core;Node.js;React Native;Xamarin,Microsoft Teams;Microsoft Azure,Jira;Github;Microsoft Teams;Microsoft Azure;Go...,No,Extremely important,Critically important,Better compensation;Wanting to work with new t...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Yes,No,Occasionally: 1-2 days per quarter but less th...,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,Windows,20 to 99 employees,Linux,Docker;Linux;Raspberry Pi;Windows;WordPress,I have little or no influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,A few times per week,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Vue.js,Angular;ASP.NET;ASP.NET Core;Django;Express;Fl...,A lot more welcome now than last year,40.0,5,3

In [27]:
df.describe()

               Age     CompTotal  ConvertedComp  WorkWeekHrs
count  2709.000000  2.138000e+03   2.131000e+03  2446.000000
mean     32.781211  4.677268e+45   1.453171e+05    40.923140
std      10.557782  2.162699e+47   2.931814e+05    13.413436
min      11.000000  0.000000e+00   0.000000e+00     4.000000
25%      25.000000  4.856250e+04   4.608950e+04    40.000000
50%      31.000000  8.500000e+04   8.107400e+04    40.000000
75%      38.000000  1.300000e+05   1.280000e+05    42.000000
max      99.000000  1.000000e+49   2.000000e+06   375.000000

In [28]:
df['OpSys'].value_counts()

Windows        1502
MacOS           844
Linux-based     707
BSD               3
Name: OpSys, dtype: int64

In [29]:
df['Country'].value_counts()

United States                  1554
Canada                          289
United Kingdom                  166
Germany                         125
India                           117
                               ...
Haiti                             1
Panama                            1
United Republic of Tanzania       1
Sudan                             1
Singapore                         1
Name: Country, Length: 98, dtype: int64

In [30]:
country_grp = df.groupby(['Country'])

In [31]:
country_grp['DatabaseWorkedWith'].value_counts().head(50)

Country      DatabaseWorkedWith
Afghanistan  MongoDB;MySQL                                                                                                 1
Albania      Oracle                                                                                                        1
Algeria      MySQL;Oracle                                                                                                  1
             MySQL;PostgreSQL                                                                                              1
             MySQL;SQLite                                                                                                  1
Argentina    Cassandra;Firebase;Microsoft SQL Server;MongoDB;MySQL;Oracle;PostgreSQL                                       1
             DynamoDB;Elasticsearch;Firebase;MariaDB;MySQL;PostgreSQL;Redis                                                1
             DynamoDB;MySQL                                                                                                1
             Firebase                                                                                                      1
             MariaDB;Microsoft SQL Server;MySQL                                                                            1
             MariaDB;MySQL                                                                                                 1
             Microsoft SQL Server;MongoDB                                                                                  1
             Microsoft SQL Server;MySQL;PostgreSQL                                                                         1
             Microsoft SQL Server;MySQL;SQLite                                                                             1
             Microsoft SQL Server;PostgreSQL                                                                               1
             Microsoft SQL Server;SQLite                                                                                   1
             MySQL                                                                                                         1
             MySQL;Oracle;SQLite                                                                                           1
             PostgreSQL                                                                                                    1
             SQLite                                                                                                        1
Armenia      Elasticsearch;Firebase;MariaDB;MongoDB;MySQL                                                                  1
             Firebase;Microsoft SQL Server;MongoDB;PostgreSQL;Redis                                                        1
             MySQL                                                                                                         1
Australia    Elasticsearch;MariaDB;Microsoft SQL Server;MySQL;Redis;SQLite                                                 1
             MariaDB;Microsoft SQL Server;PostgreSQL                                                                       1
Austria      MySQL                                                                                                         3
             Cassandra;Elasticsearch;Firebase;MariaDB;Microsoft SQL Server;MongoDB;MySQL;Oracle;PostgreSQL;Redis;SQLite    1
             Couchbase;MongoDB;Redis                                                                                       1
             Firebase                                                                                                      1
             Firebase;Microsoft SQL Server;MySQL;PostgreSQL;SQLite                                                         1
             Firebase;MySQL;PostgreSQL;SQLite                                                                              1
             MariaDB;MySQL                                                                                                 1
             Microsoft SQL Server                                                                                          1
             Microsoft SQL Server;MySQL;Oracle;PostgreSQL                                                                  1
             Microsoft SQL Server;MySQL;SQLite                                                                             1
             Microsoft SQL Server;Oracle                                                                                   1
             MongoDB                                                                                                       1
             MongoDB;PostgreSQL                                                                                            1
             MySQL;PostgreSQL;SQLite                                                                                       1
             Oracle                                                                                                        1
             Oracle;PostgreSQL                                                                                             1
             PostgreSQL                                                                                                    1
Azerbaijan   MariaDB;MySQL;PostgreSQL                                                                                      1
Bangladesh   Microsoft SQL Server                                                                                          3
             MySQL                                                                                                         2
             Elasticsearch;MariaDB;MongoDB;MySQL;Redis                                                                     1
             Elasticsearch;MySQL;Redis                                                                                     1
             Firebase;MongoDB;MySQL                                                                                        1
             MongoDB;MySQL                                                                                                 1
             MongoDB;MySQL;Redis;SQLite                                                                                    1
Name: DatabaseWorkedWith, dtype: int64

In [37]:
%matplotlib inline
import matplotlib.pyplot as plt
xlabel = 'Country'
ylabel = 'DatabaseWorkedWith'
# plt.plot(x='Country', y='DatabaseWorkedWith')
# plt.plot(xlabel, ylabel, label = 'linear', data =df) --not working
# plt.show()
# import numpy as np

# # Prepare the data
# x = np.linspace(0, 10, 100)

# # Plot the data
# plt.plot(x, x, label='linear')

# # Add a legend
# plt.legend()

# # Show the plot
# plt.show()

In [33]:
# to get the result in % format
country_grp['DatabaseWorkedWith'].value_counts(normalize = True).loc['India']

DatabaseWorkedWith
MySQL                      0.115385
Microsoft SQL Server       0.038462
MongoDB;MySQL              0.038462
MySQL;SQLite               0.038462
Firebase                   0.028846
                             ...
MySQL;PostgreSQL;Redis     0.009615
MySQL;PostgreSQL;SQLite    0.009615
Oracle                     0.009615
PostgreSQL;Redis           0.009615
Redis                      0.009615
Name: DatabaseWorkedWith, Length: 68, dtype: float64

In [36]:
filt = df['Country'] == 'India'
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

44

In [45]:
Country_uses_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

In [47]:
country_respondents = df['Country'].value_counts()

In [48]:
python_df = pd.concat([country_respondents, Country_uses_python], axis = 'columns', sort = False)
python_df

                             Country  LanguageWorkedWith
United States                   1554                 743
Canada                           289                 124
United Kingdom                   166                  69
Germany                          125                  56
India                            117                  44
...                              ...                 ...
Haiti                              1                   0
Panama                             1                   0
United Republic of Tanzania        1                   1
Sudan                              1                   0
Singapore                          1                   0

[98 rows x 2 columns]

In [51]:
python_df.rename(columns={'Country':'NumRespond','LanguageWorkedWith': 'NumKnowsPthon'}, inplace=True)

In [52]:
python_df

                             NumRespond  NumKnowsPthon
United States                      1554            743
Canada                              289            124
United Kingdom                      166             69
Germany                             125             56
India                               117             44
...                                 ...            ...
Haiti                                 1              0
Panama                                1              0
United Republic of Tanzania           1              1
Sudan                                 1              0
Singapore                             1              0

[98 rows x 2 columns]

In [53]:
python_df['PctknowsPy'] = (python_df['NumKnowsPthon']/python_df['NumRespond'])*100

In [57]:
python_df.sort_values(by='PctknowsPy', ascending=False).head(50)

                                      NumRespond  NumKnowsPthon  PctknowsPy
Uganda                                         2              2  100.000000
Algeria                                        3              3  100.000000
United Republic of Tanzania                    1              1  100.000000
Honduras                                       1              1  100.000000
Republic of Moldova                            1              1  100.000000
Syrian Arab Republic                           1              1  100.000000
Luxembourg                                     1              1  100.000000
Viet Nam                                       2              2  100.000000
China                                          3              3  100.000000
Sri Lanka                                      4              3   75.000000
Estonia                                        3              2   66.666667
Armenia                                        3              2   66.666667
Australia                                      3              2   66.666667
Guatemala                                      3              2   66.666667
Venezuela, Bolivarian Republic of...           3              2   66.666667
Serbia                                         9              6   66.666667
Chile                                          8              5   62.500000
Nigeria                                        5              3   60.000000
Ukraine                                       16              9   56.250000
Finland                                       19             10   52.631579
Indonesia                                      2              1   50.000000
Bosnia and Herzegovina                         2              1   50.000000
Georgia                                        4              2   50.000000
Czech Republic                                12              6   50.000000
Nomadic                                        4              2   50.000000
Ecuador                                        4              2   50.000000
Uruguay                                        4              2   50.000000
Jordan                                         2              1   50.000000
Dominican Republic                             2              1   50.000000
Cyprus                                         2              1   50.000000
Albania                                        2              1   50.000000
United Arab Emirates                           2              1   50.000000
Taiwan                                         2              1   50.000000
Russian Federation                            31             15   48.387097
United States                               1554            743   47.812098
Germany                                      125             56   44.800000
Egypt                                          9              4   44.444444
Netherlands                                   37             16   43.243243
Canada                                       289            124   42.906574
Bulgaria                                       7              3   42.857143
Norway                                        14              6   42.857143
Iran                                          19              8   42.105263
Israel                                        24             10   41.666667
United Kingdom                               166             69   41.566265
France                                        53             22   41.509434
Slovenia                                       5              2   40.000000
Hungary                                       10              4   40.000000
Mexico                                        30             12   40.000000
Italy                                         33             13   39.393939
Brazil                                        72             28   38.888889